title: Jing Liu
position: Ph.D. student
affiliation: Beijing Normal University
email: jing.liu@mail.bnu.edu.cn
# keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=MI6oTxsAAAAJ&hl=en
github_link: https://github.com/bnuliujing
linkedin: https://www.linkedin.com/in/%E6%99%B6-%E5%88%98-03ab59bb
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
# favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png
# description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
# canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
